### ISSUE TITLE
Create Rails Backend

### ISSUE THREAD

**Issue by eric-holdener** [eric-holdener/budgeting-app#2]
### **Overview**
Rails Backend needs to be created in order for the app to be deployed to production for multiple people to use.

### **Tables**

- User
- Cash_flow
- Investments
- Goals

### **Tasks**

- [ ] Implement SQL schema
- [ ] Create relations between models
- [ ] Create APIs to serve to frontend
- [ ] Implement user authentication
