### ISSUE TITLE
User Authentication

### ISSUE THREAD

**Issue by eric-holdener** [eric-holdener/budgeting-app#3]
### **Overview**
Each user will have their own data to access to manage their budgets. User authentication between the React frontend and Rails backend needs to be created to allow for this functionality.

### **Tasks**

- [ ] Research implementation
- [ ] Implement authentication in the backend
- [ ] Test authentication
- [ ] Implement authentication calls in the frontend
- [ ] Implement user context and protected routes in React
- [ ] Add user sign up page
- [ ] Add forgot password functionality
