### ISSUE TITLE
Create React Frontend

### ISSUE THREAD

**Issue by eric-holdener** [eric-holdener/budgeting-app#4]
### **Overview**
Rails backend will be served to a react frontend for user experience purposes

### **Tasks**

- [ ] Brainstorm potential components needed
- [ ] Create folder / file structure
- [ ] Implement react routing
- [ ] Create all components (individual issues for each component)
