### ISSUE TITLE
Integrations

### ISSUE THREAD

**Issue by eric-holdener** [eric-holdener/budgeting-app#6]
### **Overview**
Potential extension of the app. Implement integrations with banks to read purchases automatically. Only going to implement if I am 100% confident in the security.

### **Task List**

- [ ] Research integration between banks and app
- [ ] Research security behind integration
- [ ] Potentially write more tasks
