### ISSUE TITLE
Visualizations Component

### ISSUE THREAD

**Issue by eric-holdener** [eric-holdener/budgeting-app#7]
### **Overview**
App will be able to visualize monetary flow.

### **Tasks**

- [ ] Research graphing capabilities
- [ ] Add graph components to react
- [ ] Implement graphs
- [ ] Add filtering and customization to graphs
